url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "shashank-b-m.github.io" # the subpath of your site, e.g. /blog
title: "Shashank B M- Personal website" # the name of your site, e.g. ACME Corp.

sass:
  sass_dir: css
  # style:    compressed


# Social icons
show_social_icons: false
github_username: someGithubUser
twitter_username: someTwitterUser
